server {
    listen 80;
    server_name cloudbuild.tech www.cloudbuild.tech admin.cloudbuild.tech 16.171.154.28;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # API → admin container
    location /api/ {
        proxy_pass http://cloudbuild_admin:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Uploads → admin container
    location /uploads/ {
        proxy_pass http://cloudbuild_admin:3001/uploads/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    # Frontend
    location / {
        proxy_pass http://cloudbuild_frontend:80;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
